sonar.organization=group19
sonar.projectKey=ti-yu_sopra-fs26-group-19-client

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./src
